from __future__ import annotations

from pdomain_book_tools.typography.alignment import (
    AlignmentConfig,
    AlignmentEdit,
    AlignmentEditKind,
    ProjectedBoundingBox,
    ProjectedStyleSpan,
    TokenAlignmentResult,
    align_tokens,
    project_style_span,
    project_token_ranges,
)
from pdomain_book_tools.typography.annotations import TypographyAnnotations
from pdomain_book_tools.typography.labels import (
    ConfidenceTier,
    KnowledgeState,
    LabelSource,
    StyleLabel,
)
from pdomain_book_tools.typography.normalization import (
    ComparisonOperation,
    ComparisonOperationKind,
    ComparisonView,
    build_comparison_view,
    small_caps_ranges_from_spans,
)
from pdomain_book_tools.typography.records import (
    AlignmentEvidence,
    AlignmentPathOperation,
    ArtifactRef,
    ArtifactSource,
    Grapheme,
    OcrTokenRef,
    ParserControlEvidence,
    ParserControlKind,
    ParserNormalizationEvidence,
    ParserNormalizationKind,
    ParserNoteEvidence,
    ParserNoteStatus,
    SourceCoordinateSpace,
    TargetCoordinateSpace,
    TextIdentity,
    TypographyPageRecord,
)
from pdomain_book_tools.typography.spans import (
    GRAPHEME_SEGMENTATION_VERSION,
    SourceSlice,
    StyleSpan,
    TypographySpans,
    split_graphemes,
)

__all__ = [
    "GRAPHEME_SEGMENTATION_VERSION",
    "AlignmentConfig",
    "AlignmentEdit",
    "AlignmentEditKind",
    "AlignmentEvidence",
    "AlignmentPathOperation",
    "ArtifactRef",
    "ArtifactSource",
    "ComparisonOperation",
    "ComparisonOperationKind",
    "ComparisonView",
    "ConfidenceTier",
    "Grapheme",
    "KnowledgeState",
    "LabelSource",
    "OcrTokenRef",
    "ParserControlEvidence",
    "ParserControlKind",
    "ParserNormalizationEvidence",
    "ParserNormalizationKind",
    "ParserNoteEvidence",
    "ParserNoteStatus",
    "ProjectedBoundingBox",
    "ProjectedStyleSpan",
    "SourceCoordinateSpace",
    "SourceSlice",
    "StyleLabel",
    "StyleSpan",
    "TargetCoordinateSpace",
    "TextIdentity",
    "TokenAlignmentResult",
    "TypographyAnnotations",
    "TypographyPageRecord",
    "TypographySpans",
    "align_tokens",
    "build_comparison_view",
    "project_style_span",
    "project_token_ranges",
    "small_caps_ranges_from_spans",
    "split_graphemes",
]
