"""Curated common-word lexicon for the cursive drop-cap letter inference.

Iteration A's `pdomain_book_tools.ocr.dropcap` infers the drop-cap letter by
prepending each ASCII uppercase letter to the post-cap body word and
checking for a unique match in this lexicon.

Design choices:

- **Uppercase only.** Drop-cap body words inherit the cap's casing on
  the first letter; the rest of the body word is whatever the OCR
  reported. We uppercase both sides before comparison, so the lexicon
  carries uppercase entries.
- **Common-word focus.** The lexicon must be large enough to recognise
  the typical chapter-opener words (``STUDIES``, ``SUPERSTITIONS``,
  ``ONCE``, …) but small enough that ``A``-prepended fragments
  ``ANCE``/``INCE``/``ENCE`` don't all match. Rare archaic words are
  excluded on purpose so the unique-match heuristic has a chance.
- **Iteration B** will likely swap this for a proper PD-licensed
  wordlist data file (a `.txt` shipped under
  `pdomain_book_tools/ocr/data/`). Iteration A keeps the dependency surface
  zero by inlining the list.

The wordlist intentionally biases toward chapter-opener vocabulary:
common nouns/verbs/adjectives 4+ letters that typical 19th-century
prose uses to start a chapter or paragraph (the contexts where drop
caps appear). Padding with ultra-common short words like ``THE`` /
``AND`` would only hurt — drop-cap body fragments are by construction
N-1 letters, and ``THE`` minus ``T`` is ``HE`` which is also a real
word. The whole inference is "the chapter-opener word", not "any word".
"""

from __future__ import annotations

from typing import Final

# Hand-curated common English words 4+ letters. Kept terse on purpose —
# Iteration B replaces this with a data file. Anything added here MUST
# be uppercase ASCII; no apostrophes, hyphens, or non-ASCII letters.
#
# Grouped roughly by initial letter to keep the diff readable when
# Iteration B regenerates the list from a PD dictionary.
_COMMON_WORDS: Final[tuple[str, ...]] = (
    # A
    "ABOUT",
    "ABOVE",
    "ACCORDING",
    "ACROSS",
    "ACTION",
    "ACTUAL",
    "ACTUALLY",
    "AFRAID",
    "AFTER",
    "AFTERWARDS",
    "AGAIN",
    "AGAINST",
    "ALMOST",
    "ALONE",
    "ALONG",
    "ALREADY",
    "ALSO",
    "ALTHOUGH",
    "ALWAYS",
    "AMERICAN",
    "AMONG",
    "ANCIENT",
    "ANOTHER",
    "ANSWER",
    "ANSWERED",
    "APPEAR",
    "APPEARED",
    "AROUND",
    "ARRIVED",
    "ASKED",
    "AWAY",
    # B
    "BECAME",
    "BECAUSE",
    "BECOME",
    "BEEN",
    "BEFORE",
    "BEGAN",
    "BEGINNING",
    "BEGUN",
    "BEHIND",
    "BEING",
    "BELIEF",
    "BELIEVE",
    "BELIEVED",
    "BELOW",
    "BENEATH",
    "BESIDE",
    "BETTER",
    "BETWEEN",
    "BEYOND",
    "BIRDS",
    "BLACK",
    "BLOOD",
    "BOOK",
    "BOOKS",
    "BORN",
    "BOTH",
    "BRIGHT",
    "BROTHER",
    "BROUGHT",
    "BUILD",
    # C
    "CALLED",
    "CAME",
    "CANNOT",
    "CARRIED",
    "CATCH",
    "CAUGHT",
    "CENTURY",
    "CERTAIN",
    "CHAPTER",
    "CHILD",
    "CHILDREN",
    "CHURCH",
    "CLOSE",
    "COMING",
    "COMMON",
    "COULD",
    "COUNTRY",
    "COURSE",
    "CREDULITY",
    # D
    "DARK",
    "DAYS",
    "DEAD",
    "DEATH",
    "DECIDED",
    "DESCRIBED",
    "DOWN",
    "DURING",
    # E
    "EACH",
    "EARLY",
    "EARTH",
    "EITHER",
    "ELDER",
    "ELEVEN",
    "ENGLAND",
    "ENGLISH",
    "ENOUGH",
    "ENTERED",
    "EVEN",
    "EVENING",
    "EVER",
    "EVERY",
    "EXCEPT",
    # F
    "FAIR",
    "FAITH",
    "FAMILY",
    "FAMOUS",
    "FATHER",
    "FEET",
    "FELLOW",
    "FELT",
    "FEW",
    "FIELD",
    "FINAL",
    "FINDING",
    "FIRE",
    "FIRST",
    "FIVE",
    "FOLLOWED",
    "FOLLOWING",
    "FOOD",
    "FORCE",
    "FORM",
    "FORMER",
    "FOUND",
    "FOUR",
    "FRIEND",
    "FROM",
    # G
    "GAVE",
    "GIRL",
    "GIVEN",
    "GIVING",
    "GOING",
    "GONE",
    "GOOD",
    "GREAT",
    "GREEN",
    "GROUND",
    "GROUP",
    "GROWN",
    # H
    "HAND",
    "HANDS",
    "HAPPENED",
    "HARD",
    "HAVE",
    "HAVING",
    "HEAD",
    "HEARD",
    "HEART",
    "HEAVEN",
    "HELD",
    "HELP",
    "HENCE",
    "HERE",
    "HIGH",
    "HIMSELF",
    "HISTORY",
    "HOLD",
    "HOLY",
    "HOME",
    "HOPE",
    "HORSE",
    "HOUR",
    "HOURS",
    "HOUSE",
    "HOWEVER",
    "HUMAN",
    "HUNDRED",
    # I
    "IDEA",
    "INDEED",
    "INSIDE",
    "INSTEAD",
    "INTERESTING",
    "INTO",
    "ITALY",
    "ITS",
    "ITSELF",
    # J
    "JOURNEY",
    "JUST",
    # K
    "KEEP",
    "KIND",
    "KING",
    "KNEW",
    "KNOW",
    "KNOWING",
    "KNOWLEDGE",
    "KNOWN",
    # L
    "LADY",
    "LAKE",
    "LAND",
    "LARGE",
    "LAST",
    "LATE",
    "LATER",
    "LATIN",
    "LEARN",
    "LEAST",
    "LEAVING",
    "LEFT",
    "LESS",
    "LETTER",
    "LETTERS",
    "LIFE",
    "LIGHT",
    "LIKE",
    "LIST",
    "LITTLE",
    "LIVED",
    "LIVING",
    "LONG",
    "LONGER",
    "LOOK",
    "LOOKED",
    "LOOKING",
    "LORD",
    "LOST",
    "LOVE",
    "LOVED",
    "LOWER",
    # M
    "MADE",
    "MAKE",
    "MAKING",
    "MANY",
    "MARKED",
    "MASTER",
    "MATTER",
    "MEANT",
    "MEMBER",
    "MEMORY",
    "MENTIONED",
    "MIGHT",
    "MIND",
    "MOMENT",
    "MONEY",
    "MONTH",
    "MORE",
    "MORNING",
    "MOST",
    "MOTHER",
    "MOUNTAIN",
    "MOUTH",
    "MOVED",
    "MUCH",
    "MUST",
    "MYSELF",
    "MYSTERIES",
    "MYSTERIOUS",
    "MYSTERY",
    # N
    "NAME",
    "NAMED",
    "NAMES",
    "NATIONAL",
    "NATIVE",
    "NATURE",
    "NEAR",
    "NEARLY",
    "NEEDED",
    "NEVER",
    "NEXT",
    "NIGHT",
    "NORTH",
    "NOTHING",
    "NOTICED",
    "NUMBER",
    # O
    "OFTEN",
    "OLD",
    "ONCE",
    "ONLY",
    "OPEN",
    "OPENED",
    "ORDER",
    "ORIGINAL",
    "OTHER",
    "OTHERS",
    "OURSELVES",
    "OUTSIDE",
    "OVER",
    "OWN",
    # P
    "PAGE",
    "PART",
    "PASSED",
    "PEOPLE",
    "PERFECT",
    "PERHAPS",
    "PERIOD",
    "PERSON",
    "PIECE",
    "PLACE",
    "PLACED",
    "POINT",
    "POINTED",
    "POOR",
    "POSSIBLE",
    "POWER",
    "PRESENCE",
    "PRESENT",
    "PROBABLY",
    "PUBLIC",
    "PUT",
    # Q
    "QUEEN",
    "QUESTION",
    "QUICK",
    "QUIET",
    "QUITE",
    # R
    "RAIN",
    "RATHER",
    "READING",
    "REAL",
    "REALLY",
    "REASON",
    "RECEIVED",
    "RECORD",
    "RELATED",
    "REMAINED",
    "REMEMBERED",
    "RETURN",
    "RETURNED",
    "RICH",
    "RIGHT",
    "RIVER",
    "ROAD",
    "ROCK",
    "ROMAN",
    "ROUND",
    "ROYAL",
    # S
    "SAID",
    "SAME",
    "SAYING",
    "SCHOOL",
    "SECOND",
    "SEEMED",
    "SEEN",
    "SELF",
    "SENT",
    "SEVEN",
    "SEVERAL",
    "SHALL",
    "SHARP",
    "SHIP",
    "SHIPS",
    "SHORT",
    "SHOULD",
    "SIDE",
    "SILENT",
    "SILVER",
    "SINCE",
    "SISTER",
    "SIXTEEN",
    "SLOWLY",
    "SMALL",
    "SOLD",
    "SOME",
    "SOMETHING",
    "SOMETIMES",
    "SONG",
    "SOON",
    "SOUL",
    "SOUND",
    "SOURCE",
    "SOUTH",
    "SPENT",
    "SPIRIT",
    "SPOKE",
    "STAND",
    "STILL",
    "STONE",
    "STOOD",
    "STOPPED",
    "STORY",
    "STREET",
    "STRONG",
    "STUDIED",
    "STUDIES",
    "STUDY",
    "SUBJECT",
    "SUCH",
    "SUDDENLY",
    "SUMMER",
    "SUPERSTITION",
    "SUPERSTITIONS",
    "SURE",
    "SYSTEM",
    # T
    "TABLE",
    "TAKE",
    "TAKEN",
    "TAKING",
    "TALKING",
    "TAUGHT",
    "TELL",
    "TEN",
    "THAN",
    "THAT",
    "THEIR",
    "THEM",
    "THEMSELVES",
    "THEN",
    "THERE",
    "THESE",
    "THEY",
    "THING",
    "THINGS",
    "THINK",
    "THIRD",
    "THIS",
    "THOSE",
    "THOUGH",
    "THOUGHT",
    "THREE",
    "THROUGH",
    "THROUGHOUT",
    "TIME",
    "TIMES",
    "TOGETHER",
    "TOLD",
    "TOOK",
    "TOWARD",
    "TOWN",
    "TRADE",
    "TRIED",
    "TRUE",
    "TRULY",
    "TRUTH",
    "TURNED",
    "TWELVE",
    "TWENTY",
    "TYPE",
    # U
    "UNDER",
    "UNDERSTAND",
    "UNDERSTOOD",
    "UNTIL",
    "UPON",
    "USED",
    # V
    "VALUE",
    "VARIOUS",
    "VERY",
    "VICTORY",
    "VIEW",
    "VILLAGE",
    "VOICE",
    # W
    "WAITING",
    "WALKED",
    "WALKING",
    "WANT",
    "WANTED",
    "WAS",
    "WATER",
    "WAYS",
    "WEEK",
    "WELL",
    "WENT",
    "WERE",
    "WEST",
    "WHAT",
    "WHEN",
    "WHERE",
    "WHETHER",
    "WHICH",
    "WHILE",
    "WHITE",
    "WHOLE",
    "WHOSE",
    "WIDE",
    "WILD",
    "WIND",
    "WITH",
    "WITHIN",
    "WITHOUT",
    "WOMAN",
    "WONDER",
    "WORDS",
    "WORE",
    "WORK",
    "WORLD",
    "WOULD",
    "WRITTEN",
    "WRONG",
    # Y
    "YEAR",
    "YEARS",
    "YOUNG",
    "YOUR",
    "YOURSELF",
)


WORDS: Final[frozenset[str]] = frozenset(_COMMON_WORDS)
