"""Public immutable contracts for source-neutral OCR-to-text matching."""

from __future__ import annotations

from pdomain_book_tools.matching.engine import match_documents
from pdomain_book_tools.matching.legacy_projection import (
    LegacyDocumentSide,
    LegacyMatchEvidence,
    LegacyProjectionMutation,
    LegacyProjectionResult,
    legacy_page_to_match_document,
    project_match_graph_onto_page,
)
from pdomain_book_tools.matching.models import (
    ArtifactRange,
    MatchAlternative,
    MatchComparisonNormalization,
    MatchContinuationReference,
    MatchDocument,
    MatchGraph,
    MatchLine,
    MatchOperation,
    MatchOperationKind,
    MatchPage,
    MatchPolicy,
    MatchQuarantineReason,
    MatchRelation,
    MatchRelationKind,
    MatchSearchEvidence,
    MatchSearchPathEvidence,
    MatchTieBreakRule,
    MatchToken,
    canonical_relation_path_bytes,
)
from pdomain_book_tools.matching.pgdp_continuations import (
    PgdpContinuation,
    PgdpContinuationBoundary,
    PgdpContinuationDecision,
    PgdpContinuationDecode,
    PgdpContinuationQuarantineReason,
    PgdpLogicalCandidate,
    PgdpMarkerEvidence,
    PgdpPhysicalFragment,
    PgdpQuarantinedMarker,
    PgdpRound,
    PgdpRoundContinuationEvidence,
    PgdpUnmappedMarkerEvidence,
    build_pgdp_surface_document,
    decode_pgdp_continuations,
)

__all__ = [
    "ArtifactRange",
    "LegacyDocumentSide",
    "LegacyMatchEvidence",
    "LegacyProjectionMutation",
    "LegacyProjectionResult",
    "MatchAlternative",
    "MatchComparisonNormalization",
    "MatchContinuationReference",
    "MatchDocument",
    "MatchGraph",
    "MatchLine",
    "MatchOperation",
    "MatchOperationKind",
    "MatchPage",
    "MatchPolicy",
    "MatchQuarantineReason",
    "MatchRelation",
    "MatchRelationKind",
    "MatchSearchEvidence",
    "MatchSearchPathEvidence",
    "MatchTieBreakRule",
    "MatchToken",
    "PgdpContinuation",
    "PgdpContinuationBoundary",
    "PgdpContinuationDecision",
    "PgdpContinuationDecode",
    "PgdpContinuationQuarantineReason",
    "PgdpLogicalCandidate",
    "PgdpMarkerEvidence",
    "PgdpPhysicalFragment",
    "PgdpQuarantinedMarker",
    "PgdpRound",
    "PgdpRoundContinuationEvidence",
    "PgdpUnmappedMarkerEvidence",
    "build_pgdp_surface_document",
    "canonical_relation_path_bytes",
    "decode_pgdp_continuations",
    "legacy_page_to_match_document",
    "match_documents",
    "project_match_graph_onto_page",
]
