"""Public immutable contracts for source-neutral OCR-to-text matching."""

from __future__ import annotations

from pdomain_book_tools.matching.engine import match_documents
from pdomain_book_tools.matching.models import (
    ArtifactRange,
    MatchAlternative,
    MatchDocument,
    MatchGraph,
    MatchLine,
    MatchOperation,
    MatchOperationKind,
    MatchPage,
    MatchPolicy,
    MatchQuarantineReason,
    MatchRelation,
    MatchRelationKind,
    MatchToken,
    canonical_relation_path_bytes,
)
from pdomain_book_tools.matching.pgdp_continuations import (
    PgdpContinuation,
    PgdpContinuationBoundary,
    PgdpContinuationDecision,
    PgdpContinuationDecode,
    PgdpContinuationQuarantineReason,
    PgdpLogicalCandidate,
    PgdpMarkerEvidence,
    PgdpPhysicalFragment,
    PgdpQuarantinedMarker,
    PgdpRound,
    PgdpRoundContinuationEvidence,
    PgdpUnmappedMarkerEvidence,
    decode_pgdp_continuations,
)

__all__ = [
    "ArtifactRange",
    "MatchAlternative",
    "MatchDocument",
    "MatchGraph",
    "MatchLine",
    "MatchOperation",
    "MatchOperationKind",
    "MatchPage",
    "MatchPolicy",
    "MatchQuarantineReason",
    "MatchRelation",
    "MatchRelationKind",
    "MatchToken",
    "PgdpContinuation",
    "PgdpContinuationBoundary",
    "PgdpContinuationDecision",
    "PgdpContinuationDecode",
    "PgdpContinuationQuarantineReason",
    "PgdpLogicalCandidate",
    "PgdpMarkerEvidence",
    "PgdpPhysicalFragment",
    "PgdpQuarantinedMarker",
    "PgdpRound",
    "PgdpRoundContinuationEvidence",
    "PgdpUnmappedMarkerEvidence",
    "canonical_relation_path_bytes",
    "decode_pgdp_continuations",
    "match_documents",
]
